if File.exist?('.env')
  File.foreach('.env') do |line|
    next if line.strip.empty? || line.start_with?('#')
    key, value = line.strip.split('=', 2)
    ENV[key] = value if key && value
  end
end
 
Vagrant.configure(2) do |config|

  config.vm.box = "generic/alpine318"
  config.vm.provider "libvirt" do |lv|
    lv.memory = 512
    lv.cpus = 1
    lv.driver = 'kvm'
    lv.features = ['apic']
    lv.machine_type = "q35"
    lv.cpu_mode = "custom"
    lv.cpu_model = "qemu64"
  end

  config.vm.provision "shell", inline: <<-SHELL
  echo "=== configuring c2 instead of default c1 alpine"
  apk add --no-cache cgroup-tools coreutils curl
  sed -i 's/#rc_cgroup_mode="hybrid"/rc_cgroup_mode="unified"/' /etc/conf.d/cgroups 2>/dev/null || sed -i 's/#rc_cgroup_mode="hybrid"/rc_cgroup_mode="unified"/' /etc/rc.conf
  rc-update add cgroups boot
  if ! grep -q "cgroup_no_v1=all" /etc/update-extlinux.conf; then
      sed -i 's/default_kernel_opts="/default_kernel_opts="cgroup_no_v1=all /' /etc/update-extlinux.conf
      update-extlinux
  fi
SHELL
config.vm.provision :reload
  
  # SERVER
  config.vm.define "ndelhotaS" do |master_control|
    master_control.vm.hostname = "ndelhotaS"
    master_control.vm.network "private_network", ip: ENV['K3S_SERVER_IP']
    master_control.vm.provision "shell", path: "./master_boot.sh", env: {
      "K3S_TOKEN" => ENV['K3S_TOKEN'] , "K3S_SERVER_IP" => ENV["K3S_SERVER_IP"]
    }
    master_control.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 2
    end
  end
  
  # WORKER
  config.vm.define "ndelhotaSW" do |worker_control|
    worker_control.vm.hostname = "ndelhotaSW"
    worker_control.vm.network "private_network", ip:  ENV['K3S_AGENT_IP']
    worker_control.vm.provision "shell", path: "./worker_boot.sh", env: {
        "K3S_SERVER_IP" => ENV['K3S_SERVER_IP'], "K3S_TOKEN" => ENV['K3S_TOKEN'], "K3S_AGENT_IP" => ENV['K3S_AGENT_IP']
      }
    end
end
