require 'rbconfig'

Vagrant.configure(2) do |config|
  config.vm.box = "generic/alpine318"
  
  config.vm.provider "libvirt" do |lv|
    lv.memory = 512
    lv.cpus = 1
    lv.driver = 'kvm'
    lv.features = ['apic']
    lv.machine_type = "q35"
    lv.cpu_mode = "custom"
    lv.cpu_model = "qemu64"
  end
  
  config.vm.define "ndelhotaS" do |control|
    control.vm.hostname = "ndelhotaS"
    control.vm.network "private_network", ip: ENV['K3S_SERVER_IP']
    control.vm.provider "libvirt" do |lv|
      #lv.customize ["modifyvm", :id, "--name", "ndelhotaS"]
    end
  config.vm.provision :shell, :inline => SHELL
    SHELL
    control.vm.provision "shell", path: "./worker_boot.sh"
  end
  
  config.vm.define "ndelhotaSW" do |control|
    control.vm.hostname = "ndelhotaSW"
    control.vm.network "private_network", ip:  ENV['K3S_AGENT_IP']
    control.vm.provider "libvirt" do |lv|
      #lv.customize ["modifyvm", :id, "--name", "ndelhotaSW"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      SHELL
      control.vm.provision "shell", path: "./agent_boot.sh"
    end
end
